FROM python:3.12-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY . .
RUN uv sync --package hdf_pipelines
CMD ["uv", "run", "--package", "hdf_pipelines", "kedro", "run"]
