FROM python:3.12-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY . .
RUN uv sync --package hierarchical_demand_forecasting_poc
CMD ["uv", "run", "--package", "hierarchical_demand_forecasting_poc", "kedro", "run"]
