from html import escape

import streamlit as st

from ui.components import render_hero, render_section_header
from ui.styles import apply_global_styles

st.set_page_config(
    page_title="Demand Forecast POC",
    page_icon="📈",
    layout="wide",
)

apply_global_styles()

render_hero(
    title="Demand Forecast PoC",
    subtitle=(
        "Temporal hierarchical forecasting for a critical SKU. "
        "Explore the monthly forecast, model evaluation, temporal hierarchy, "
        "and future business assistant capabilities from the sidebar."
    ),
    eyebrow="Hierarchical Demand Forecasting",
)

st.markdown(
    """
    <p class="app-muted-text">
    This PoC demonstrates a complete forecasting system — from raw demand data and exogenous
    variables through a Kedro ML pipeline to evaluated, reconciled forecasts served through
    this Streamlit application. The <strong>monthly layer is the active MVP</strong>; weekly
    and daily layers are planned enhancements.
    </p>
    """,
    unsafe_allow_html=True,
)

render_section_header(
    "App Sections",
    description="Select a page from the sidebar to navigate.",
)

_SECTIONS = [
    (
        "Monthly Forecast",
        "Active",
        "Forward-looking monthly demand forecast generated by the Prophet champion model.",
        "success",
    ),
    (
        "Evaluation Report",
        "Active",
        "Champion model selection rationale and held-out test performance metrics.",
        "success",
    ),
    (
        "Project Overview",
        "Active",
        "Live champion status, pipeline artifact health, and PoC scope summary.",
        "success",
    ),
    (
        "Weekly Anchor",
        "Planned",
        "14-week operational forecast — secondary enhancement layer.",
        "info",
    ),
    (
        "Temporal Coherence",
        "Planned",
        "Monthly ↔ Weekly reconciliation diagnostics and coherence validation.",
        "info",
    ),
    (
        "Business Assistant",
        "Planned",
        "Natural-language Q&A over forecasts, business context, and model results.",
        "info",
    ),
]

cols = st.columns(3)
for i, (name, status, desc, badge_status) in enumerate(_SECTIONS):
    with cols[i % 3]:
        st.markdown(
            f"""
            <div class="app-nav-card">
                <div class="app-nav-card-title">{escape(name)}</div>
                <div class="app-nav-card-description">{escape(desc)}</div>
                <span class="app-status-badge {badge_status}">{escape(status)}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )
