import streamlit as st

from ui.components import render_info_banner, render_page_header, render_section_header
from ui.page_blocks.placeholder_blocks import render_future_capability_block
from ui.styles import apply_global_styles

apply_global_styles()

render_page_header(
    title="Weekly Anchor Forecast",
    subtitle="Secondary operational layer — 14-week horizon complement to the monthly forecast.",
    eyebrow="Secondary Layer",
)

render_info_banner(
    title="Secondary operational layer",
    message=(
        "This page will display the 14-week weekly forecast once the weekly pipeline is "
        "validated. The monthly layer remains the active MVP and primary decision input."
    ),
)

render_future_capability_block(
    title="Weekly point forecast",
    status="Planned",
    description=(
        "Point forecasts and 80% prediction intervals for a 14-week horizon, "
        "generated by the weekly Kedro pipeline once trained and validated."
    ),
    expected_inputs=[
        "Weekly demand actuals (03_primary/)",
        "Exogenous variables (weekly granularity)",
        "Reconciled weights from the monthly layer",
    ],
    planned_outputs=[
        "weekly_forecast_raw.parquet (07_model_output/)",
        "weekly_forecast_reconciled.parquet (07_model_output/)",
    ],
)

render_future_capability_block(
    title="Model comparison — weekly layer",
    status="Planned",
    description=(
        "Side-by-side performance comparison of SARIMAX, Prophet, and CatBoost "
        "on the weekly layer, ranked by weekly MAPE and wMAPE."
    ),
    expected_inputs=[
        "Weekly train / val / test splits (05_model_input/)",
        "Trained weekly model artifacts (06_models/)",
    ],
    planned_outputs=[
        "weekly_model_selection_summary.parquet (06_models/selection/)",
        "weekly_champion_metadata.json (06_models/champions/)",
    ],
)

render_section_header(
    "Next Implementation Milestone",
    description="Steps required before weekly forecast outputs appear on this page.",
)
st.markdown("""
1. Complete weekly feature engineering pipeline (`feature_engineering_weekly`)
2. Train and tune weekly candidates (`train_weekly`)
3. Run weekly model selection (`model_selection` with weekly namespace)
4. Generate weekly forecasts via `forecast_inference`
5. Update this page to load and display `weekly_forecast_raw.parquet`
    """)
