"""Page-specific UI blocks for the Monthly Forecast page (02_Monthly_Forecast.py).

All functions receive already-loaded data and a normalized champion *identity*;
they have no knowledge of artifact paths or which model family won. The page
script (02_Monthly_Forecast.py) handles all data loading and orchestration.
"""

from html import escape

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from ui.components import (
    render_empty_state,
    render_hero,
    render_info_banner,
    render_kpi_card,
    render_section_header,
    render_warning_banner,
)
from utils.champion import family_label
from utils.formatting import (
    format_date,
    format_metric,
    format_optional,
    format_percentage,
)
from utils.paths import forecast_parquet

_HORIZON_LABELS: dict[int, str] = {3: "3 months", 6: "6 months", 12: "12 months"}
_ALL_HORIZONS: list[int] = [3, 6, 12]

_REGEN_FORECAST_CMD = "uv run kedro run --pipeline forecast_inference"


def _detect_available_horizons() -> list[int]:
    """Return the list of horizons (in months) for which forecast parquets exist."""
    return [h for h in _ALL_HORIZONS if forecast_parquet(h).exists()]


def render_monthly_page_header() -> None:
    """Render the hero banner for the Monthly Forecast page."""
    render_hero(
        title="Monthly Forecast — Primary Decision Layer",
        subtitle=(
            "Forward-looking monthly demand forecast generated by the current production "
            "champion — selected from a time-aware competition among Prophet, SARIMAX, and "
            "CatBoost. This is the primary, executive-facing forecast view."
        ),
        eyebrow="Hierarchical Demand Forecasting · Monthly Layer",
    )


def render_monthly_section_gap() -> None:
    """Render a compact spacer between monthly page sections."""
    st.markdown('<div class="monthly-section-gap"></div>', unsafe_allow_html=True)


def render_monthly_kpi_summary(identity: dict, horizon_months: int) -> None:
    """Render a row of KPI cards summarising the production champion and forecast.

    Args:
        identity: Normalized champion identity from ``extract_champion_identity``.
        horizon_months: Currently selected forecast horizon in months.
    """
    render_section_header("Production Champion Summary")

    test_metrics = identity.get("test_metrics", {})
    wape = test_metrics.get("wape")
    rmse = test_metrics.get("rmse")
    precision = test_metrics.get("forecast_precision")
    business_flag = wape is not None and wape <= 0.15
    family = family_label(identity.get("model_family"))
    champion_id = identity.get("champion_id")
    generated_at = identity.get("forecast_generated_at")
    last_run = format_date(generated_at) if generated_at else "Not available"

    wape_status = "success" if (wape is not None and wape < 0.15) else "warning"
    precision_status = "success" if business_flag else "warning"

    cols = st.columns(5)
    with cols[0]:
        render_kpi_card(
            label="Champion Family",
            value=family,
            help_text=f"ID: {format_optional(champion_id)}",
        )
    with cols[1]:
        render_kpi_card(
            label="Test WAPE",
            value=format_percentage(wape) if wape is not None else "N/A",
            help_text="Weighted Absolute % Error on test set (primary metric)",
            status=wape_status,
        )
    with cols[2]:
        render_kpi_card(
            label="Test RMSE",
            value=(
                format_metric(rmse, decimals=1, suffix=" units")
                if rmse is not None
                else "N/A"
            ),
            help_text="Root Mean Squared Error on test set",
        )
    with cols[3]:
        render_kpi_card(
            label="Forecast Precision",
            value=format_percentage(precision) if precision is not None else "N/A",
            help_text="1 − WAPE; business target ≥ 85%",
            status=precision_status,
        )
    with cols[4]:
        render_kpi_card(
            label="Selected Horizon",
            value=f"{horizon_months} months",
            help_text=f"Last forecast run: {last_run}",
        )


def render_horizon_selector() -> int:
    """Render the forecast horizon selector and return the selected horizon in months.

    Detects available horizons from existing forecast parquet files. If no horizons
    are found, falls back to a default of 6 months and shows a warning.

    Returns:
        Selected forecast horizon in months.
    """
    available = _detect_available_horizons()

    if not available:
        with st.container(key="monthly-horizon-toolbar", border=True):
            st.markdown(
                """
                <div class="monthly-toolbar-header">
                    <div class="monthly-toolbar-label">Forecast Controls</div>
                    <div class="monthly-toolbar-title">Forecast horizon</div>
                    <p class="monthly-toolbar-copy">
                        No generated forecast horizons are currently available, so the page will
                        fall back to the default 6-month view until new artifacts are produced.
                    </p>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.warning(
                "No forecast horizons found. "
                f"Run `{_REGEN_FORECAST_CMD}` to generate forecasts."
            )
        return 6

    options = [_HORIZON_LABELS[h] for h in available]
    default_idx = len(options) - 1  # longest available horizon as default
    missing = [h for h in _ALL_HORIZONS if h not in available]

    with st.container(key="monthly-horizon-toolbar", border=True):
        st.markdown(
            """
            <div class="monthly-toolbar-header">
                <div class="monthly-toolbar-label">Forecast Controls</div>
                <div class="monthly-toolbar-title">Forecast horizon</div>
                <p class="monthly-toolbar-copy">
                    Choose the executive view to compare near-term and longer-range demand outlooks.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        widget_help = (
            "Select the forward-looking forecast window to display on this page."
        )
        if hasattr(st, "segmented_control"):
            selected_label = st.segmented_control(
                "Forecast horizon",
                options=options,
                default=options[default_idx],
                selection_mode="single",
                key="monthly_forecast_horizon",
                help=widget_help,
                label_visibility="collapsed",
                width="stretch",
            )
        else:
            selected_label = st.radio(
                "Forecast horizon",
                options=options,
                index=default_idx,
                horizontal=True,
                key="monthly_forecast_horizon",
                help=widget_help,
                label_visibility="collapsed",
            )

        if missing:
            missing_labels = ", ".join(_HORIZON_LABELS[h] for h in missing)
            st.markdown(
                f"""
                <p class="monthly-toolbar-note">
                    <strong>Unavailable right now:</strong> {escape(missing_labels)}.
                    The selector only shows horizons that have generated artifacts.
                </p>
                """,
                unsafe_allow_html=True,
            )

    label_to_months = {v: k for k, v in _HORIZON_LABELS.items()}
    return label_to_months[selected_label or options[default_idx]]


def render_forecast_chart_panel(
    fig: go.Figure,
    identity: dict,
    horizon_months: int,
    has_intervals: bool,
) -> None:
    """Render the main forecast chart inside a styled section panel.

    Args:
        fig: Plotly figure returned by plot_forecast().
        identity: Normalized champion identity used to build the caption.
        horizon_months: Selected horizon in months.
        has_intervals: Whether the current champion exposes prediction intervals.
    """
    refit = identity.get("refit", {}) or {}
    test_period = identity.get("test_period", {}) or {}
    refit_start = format_date(refit.get("start_date", ""))
    refit_end = format_date(refit.get("end_date", ""))
    test_start = format_date(test_period.get("start_date", ""))
    test_end = format_date(test_period.get("end_date", ""))

    caption_parts: list[str] = []
    if refit_start != "N/A" and refit_end != "N/A":
        scope = refit.get("data_scope", "history").replace("_", " ")
        caption_parts.append(f"Refit ({scope}): {refit_start} → {refit_end}")
    if test_start != "N/A" and test_end != "N/A":
        caption_parts.append(f"Test: {test_start} → {test_end}")
    caption_parts.append(f"Horizon: {horizon_months} months forward")

    interval_copy = (
        "with prediction intervals"
        if has_intervals
        else "as a point forecast (no prediction intervals for this champion)"
    )

    with st.container(key="monthly-chart-panel", border=True):
        st.markdown(
            f"""
            <div class="monthly-chart-panel-header">
                <div class="monthly-chart-panel-label">Primary View</div>
                <div class="monthly-chart-panel-title">Demand Forecast Chart</div>
                <p class="monthly-chart-panel-copy">
                    Monthly actuals, held-out test backtesting, and the selected
                    {horizon_months}-month forward forecast {escape(interval_copy)}.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.plotly_chart(fig, use_container_width=True)
        st.markdown(
            f"""
            <div class="monthly-chart-panel-meta">
                {escape(" | ".join(caption_parts))}
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_executive_forecast_summary(
    identity: dict,
    horizon_months: int,
    future_fc: pd.DataFrame,
) -> None:
    """Render a business-facing narrative interpretation of the current forecast.

    Args:
        identity: Normalized champion identity from ``extract_champion_identity``.
        horizon_months: Currently selected forecast horizon in months.
        future_fc: Future forecast DataFrame (may be empty).
    """
    render_section_header(
        "Executive Interpretation",
        description="Business-facing summary of the current forecast output.",
    )

    test_metrics = identity.get("test_metrics", {})
    wape = test_metrics.get("wape")
    precision = test_metrics.get("forecast_precision")
    business_flag = wape is not None and wape <= 0.15
    family = family_label(identity.get("model_family"))
    champion_id = identity.get("champion_id") or "the production champion"
    precision_str = format_percentage(precision) if precision is not None else "N/A"
    target_str = "85.0%"

    if business_flag:
        status_line = (
            f"The champion has met the business precision target of {target_str}, "
            f"achieving {precision_str} on the held-out test set."
        )
    else:
        status_line = (
            f"Current forecast precision ({precision_str}) is below the business target "
            f"of {target_str}. This output should be interpreted as a functional baseline "
            "rather than a final production-ready model."
        )

    if not future_fc.empty and "yhat" in future_fc.columns:
        avg_f = future_fc["yhat"].mean()
        min_f = future_fc["yhat"].min()
        max_f = future_fc["yhat"].max()
        range_line = (
            f"Over the selected **{horizon_months}-month horizon**, projected demand ranges "
            f"from **{min_f:,.0f}** to **{max_f:,.0f}** units "
            f"(average: **{avg_f:,.0f}** units/month)."
        )
    else:
        range_line = (
            f"No future forecast data is currently available for the "
            f"{horizon_months}-month horizon."
        )

    st.markdown(f"""
The current monthly production champion is **{escape(family)}** (*{escape(str(champion_id))}*),
selected from a time-aware competition among Prophet, SARIMAX, and CatBoost. It provides the
forecast for the {horizon_months}-month horizon. {status_line}

{range_line}

> **Note:** The winning family is read from the latest model-selection artifacts and may change
> after a new pipeline run. Forecast precision targets and candidates continue to evolve as the
> project progresses toward production readiness.
        """)


def render_future_forecast_table(
    future_fc: pd.DataFrame,
    horizon_months: int,
    has_intervals: bool,
) -> None:
    """Render the future forecast values in a clean, stakeholder-friendly table.

    Args:
        future_fc: Future forecast DataFrame with ds/yhat (and optional bounds).
        horizon_months: Selected horizon in months (used for headings and filename).
        has_intervals: Whether to surface prediction-interval columns.
    """
    interval_desc = (
        "Projected monthly demand values with prediction intervals."
        if has_intervals
        else "Projected monthly demand values (point forecast — no prediction intervals)."
    )
    render_section_header(
        f"Forecast Table — {horizon_months}-Month Horizon",
        description=interval_desc,
    )

    if future_fc.empty:
        render_empty_state(
            title="No Forecast Data Available",
            message=(
                f"The {horizon_months}-month forecast artifact was not found. "
                f"Run `{_REGEN_FORECAST_CMD}` to generate it."
            ),
            status="warning",
        )
        return

    available_cols = set(future_fc.columns)
    ordered_cols = ["ds", "horizon", "yhat"]
    if has_intervals:
        ordered_cols += ["yhat_lower", "yhat_upper"]
    ordered_cols = [c for c in ordered_cols if c in available_cols]
    display = future_fc[ordered_cols].copy()

    if "ds" in display.columns:
        display["ds"] = display["ds"].dt.strftime("%b %Y")

    rename_map = {
        "ds": "Month",
        "horizon": "Step",
        "yhat": "Forecast (units)",
        "yhat_lower": "Lower Bound",
        "yhat_upper": "Upper Bound",
    }
    display = display.rename(
        columns={k: v for k, v in rename_map.items() if k in display.columns}
    )

    for col in ["Forecast (units)", "Lower Bound", "Upper Bound"]:
        if col in display.columns:
            display[col] = display[col].apply(lambda v: f"{v:,.0f}")

    st.dataframe(display, use_container_width=True, hide_index=True)

    csv_data = future_fc.to_csv(index=False)
    st.download_button(
        label="Download CSV",
        data=csv_data,
        file_name=f"monthly_forecast_{horizon_months}m.csv",
        mime="text/csv",
    )


def render_monthly_provenance(identity: dict) -> None:
    """Render a light freshness/provenance caption for the current forecast run.

    Args:
        identity: Normalized champion identity from ``extract_champion_identity``.
    """
    generated_at = identity.get("forecast_generated_at")
    run_id = identity.get("run_id")
    interval_method = identity.get("interval_method")
    parts: list[str] = []
    if generated_at:
        parts.append(f"Generated: {format_date(generated_at)}")
    if run_id:
        parts.append(f"Run: {run_id}")
    if identity.get("training_cutoff"):
        parts.append(f"Training cutoff: {format_date(identity['training_cutoff'])}")
    if identity.get("has_prediction_interval") and interval_method:
        parts.append(f"Interval method: {interval_method}")
    if parts:
        st.caption("  ·  ".join(parts))


def render_monthly_data_status() -> None:
    """Render a data availability note showing which forecast horizons are available."""
    available = _detect_available_horizons()
    missing = [h for h in _ALL_HORIZONS if h not in available]

    if missing:
        missing_str = ", ".join(f"{h}m" for h in missing)
        render_warning_banner(
            title="Some Forecast Horizons Unavailable",
            message=(
                f"The following horizons are not yet generated: {missing_str}. "
                f"Run `{_REGEN_FORECAST_CMD}` to generate all horizons."
            ),
        )
    else:
        render_info_banner(
            title="All Forecast Horizons Available",
            message=(
                "3-month, 6-month, and 12-month forecasts have all been generated "
                "and are ready for display."
            ),
        )
